scripts/vplane-sflow.pl opt/vyatta/sbin
scripts/vplane-show-sflow.py opt/vyatta/bin
scripts/vyatta-sflow.pl opt/vyatta/sbin
templates-op/clear/sflow opt/vyatta/share/vyatta-op/templates/clear
templates-op/show/sflow opt/vyatta/share/vyatta-op/templates/show
tmplscripts/interfaces/dataplane/sflow opt/vyatta/share/tmplscripts/interfaces/dataplane
yang/vyatta-service-sflow-v1.yang usr/share/configd/yang
